const endpointsPath = {
    auth: 'Auth',
    order: 'Order',
    category: 'Category',
    subCategory: 'SubCategory',
    brand: 'Brand',
    product: 'Products',
    productReview: 'ProductReview',
    slider: 'Slider',
    banner: 'Banner',
    featuredProduct: 'FeaturedProduct',
    limitedOffer: 'LimitedOffer',
    transaction: 'Transaction',
    productImage: 'ProductImage',
    productVariant: 'ProductVariant',
    productSpecification: 'ProductSpecification',
    pricingTier: 'PricingTier',
    profile: 'UserProfile',
    shipping: 'Shipping',
    userFavorite: 'user/favorite',
    store: 'store',
    propertyRecent: 'store/properties/recent',
    productAdmin: 'admin/product',
    property: 'property',
    propertyAdmin: 'admin/property',
    userAdmin: 'admin/user',
    wallet: 'Wallet',
    user: 'User',
    userDeliveryAddress: 'UserDeliveryAddress',
    deliveryLocation: 'DeliveryLocation',
    googleMap: 'GoogleMap',
    vat: 'Vat',
    checkout: 'Checkout',
    manualPayment: 'ManualPayment',
    paymentMethodConfiguration: 'PaymentMethodConfiguration',
    websiteContent: 'WebsiteContent',
    voucher: 'Voucher',
    paystack: 'Paystack',
    referral: 'Referral',
    subscriber: 'Subscriber',
    gigDelivery: 'GigDelivery',
    coupon: 'Coupon',
    tag: 'Tag',
    cart: 'Cart',

}
export default endpointsPath
